### PR TITLE
Export `collect` function

### PR DESCRIPTION
**Pull request by menelaos**

### CODE REVIEW

**Comment by paf31** [comment]
👍 but maybe we can come up with a better name. These things are usually called `somethingWithKey`. Perhaps `toArrayWithKey`?

**Comment by menelaos** [comment]
`toArrayWithKey` would be consistent with `mapWithKey` and `filterWithKey`. 
Personally, I think I would prefer `toArrayWith`, `mapWith` and `filterWith` :bike: :innocent:.

**Comment by paf31** [comment]
👍 Looks good, thanks!

@hdgarrood Do you want to merge this with your other PR and make a release, please?

**Comment by hdgarrood** [comment]
Sure :)

**Pull request merged**
