### PR TITLE
Add StrMap.mapWithKey

### PR DESCRIPTION
**Pull request by joshuahhh**
Please take a look! Thanks. 😃 

P.S. I added a test for Map.mapWithKey while I was at it.

### CODE REVIEW

**Comment by garyb** [comment]
Looks good to me 👍

**Comment by garyb** [comment]
I think the tests will pass when we finish updating the core libraries, this is due to `transformers` needing functional dependencies adding for the latest compiler.

**Comment by paf31** [comment]
👍 Looks great, thanks!

**Comment by garyb** [comment]
Merged as #74. Thanks!

**Pull request closed without merging**
