### PR TITLE
fix some other instances of hasOwnProperty being called directly

### PR DESCRIPTION
**Pull request by jbrownson**
Do we want to fix these while we're at it in the same fashion?

### CODE REVIEW

**Comment by paf31** [comment]
:+1:

**Comment by jbrownson** [comment]
This article is relevant: http://www.2ality.com/2012/01/objects-as-maps.html

We should probably use the .keys() function instead of for to enumerate keys too?

**Comment by michaelficarra** [comment]
Nice work. I was planning on sending a PR tonight to avoid the `__proto__` issue mentioned in that article (as well as this one). The general idea is we'll run every key through a `safeKey` function that transforms it so that it's impossible to arrive at a key of `__proto__`, `hasOwnProperty`, or anything on `Object.prototype`.

**Comment by jbrownson** [comment]
#45 is more complete than this one, closing

**Pull request closed without merging**
