### PR TITLE
use generic instances in tests

### PR DESCRIPTION
**Pull request by matthewleon**
eliminates some boilerplate in the tests by using purescript-generics-rep

### CODE REVIEW

**Comment by hdgarrood** [comment]
No need to pull Generic in: we can derive `Eq` and `Ord` directly :smile: https://github.com/purescript/purescript/releases/tag/v0.8.2

**Comment by hdgarrood** [comment]
Oh oops, we can't derive `Show` so we do need `Generic` if we want that. Hm, I'm tempted to leave the `Show` instance as-is just because the dependency graph of the core libraries can be somewhat difficult to deal with, so I'm not sure adding a dependency on `Generic` is worth it.

**Comment by matthewleon** [comment]
Good points. Will create a new PR that just uses the automatic derivation of Eq.

**Comment by matthewleon** [comment]
Actually just wanted to be sure re: the dep graph. The dependency is only added as a dev dependency. Does it still pose a problem?

**Comment by hdgarrood** [comment]
Yes, I think so - if we added `generics` to this library's devDependencies, we might later add a (regular) dependency on `maps` from `generics` without realising that this will cause problems for anyone trying to install dev dependencies in this project.

**Comment by matthewleon** [comment]
understood. will make the separate PR that doesn't include generics.

**Pull request closed without merging**
