### PR TITLE
Add lookup{LT,LE,GT,GE}, find{Min,Max}

### LINKED ISSUE #52: Add lookupGT and lookupLE?
I looked into this but it wasn't immediately obvious how to implement these.

### PR DESCRIPTION
**Pull request by mtolly**
Closes #52. I needed the lookupXX functions to port some GHCJS code, and then I needed findMin/findMax to implement lookupLT/GT so I figured I'd export those as well.

All the functions also have thorough tests. I am new to PureScript so do let me know if you want any style changes or things like that :)

### CODE REVIEW

**Comment by garyb** [comment]
Looks good to me :+1: 

@paf31?

**Comment by paf31** [comment]
Looks great, but can we save some duplication by reversing orders perhaps? I'm not fussed either way, really, since the tests pass.

:+1: Thanks!

**Comment by mtolly** [comment]
Sorry this dropped off my radar for a bit. Possibly you could condense them, but I don't see how to do it both elegantly and efficiently. You'd have to flip the whole tree *and* also reverse the comparison operator (probably with [the `Down` wrapper](https://github.com/purescript/purescript-orders/blob/dc875c8/src/Data/Ord.purs#L19-L25)). That'd be too much overhead for my tastes. Or you could have a shared implementation take a `Boolean` to make every left/right decision, but I think that'd make the code a lot less readable. If there were more potential savings it might make sense but here it seems not worth it.

**Comment by mtolly** [comment]
While I've got this PR open, would you be open to another PR that adds an `Internal`/`Unsafe`/similarly-named module exporting the `Map` constructors? I've had to write some fairly specialized functions for efficient `Map` traversal (https://github.com/mtolly/onyxite-customs/blob/faf480b/player/src/OnyxMap.purs#L383-L421) that require access to the constructors, so currently I'm using a local modified version of the module and it would be nice to not have to (i.e. less code to manage + smaller compiled blob size).

**Comment by mtolly** [comment]
Is this ready to be merged?

**Comment by garyb** [comment]
Can you rebase it please?

**Comment by mtolly** [comment]
Done, and updated to PS 0.9.1.

**Comment by garyb** [comment]
Thanks very much!

**Comment by garyb** [comment]
And sorry it got left for so long.

**Pull request merged**
