### PR TITLE
avoid collision with Object.prototype keys in StrMap using key transformation function

### PR DESCRIPTION
**Pull request by michaelficarra**
This builds on top of #44 by @jbrownson. Not sure yet how to avoid duplicating the `safeKey` function in each `.js` file. I'd love to hear a suggestion.

### CODE REVIEW

**Comment by jbrownson** [comment]
Reviewed it, I don't find anything you missed :+1: . I did notice a completely unrelated copy/paste doc error though I'll open a pr for in a min :).

It seems like this is harder to review than it could be, like we could be more cleanly exposing the javascript string map model and writing more of this in the .purs files, but maybe that's harder than it looks? Probably not worth it at this point.

**Comment by jbrownson** [comment]
I'll close my PR as this definitely is more complete, and I don't think we can avoid the extra perf hit of manipulating the strings.

**Comment by michaelficarra** [comment]
I'd also like to add regression tests to ensure we continue to support keys named `hasOwnProperty`, `__proto__`, `toString`, etc.

**Comment by paf31** [comment]
This will break any existing code which uses `StrMap` for typing foreign functions. A search on GitHub reveals a few libraries which assume the existing representation.

Is it possible to create objects without a prototype? `Object.create(null)` perhaps?

**Comment by michaelficarra** [comment]
I imagine the performance impact of that will be considerable, but I will run a benchmark next opportunity I get.

**Comment by michaelficarra** [comment]
Oh, additionally that will mean dropping ES3 support. Not a big deal for me, but I'm sure it is for some people.

**Comment by jbrownson** [comment]
Thought this needed a polite bump.

It looks like we're primarily hung up on possibly breaking uses of this to type against FFI stuff. It seems like a thing designed to be used that way belongs in purescript-foreign? I see there's an Object type there, but maybe an ObjectMap or something would be appropriate along w/ a major version bump here to make the incompatibility clear?

**Comment by paf31** [comment]
`purescript-css` and `purescript-node-http` are two projects which assume the existing representation. Each foreign type should document its runtime representation, and it would definitely be a breaking change to modify that IMO. This library _sort of_ documents is representation, and it probably should be clearer about it.

I would prefer, if possible, to keep the current representation. Even if we moved something like this into `purescript-foreign`, you still have to deal with the case where you programmatically access keys like `hasOwnProperty`. If you want to treat the object like a general-purpose map, like the libraries above do, then it's still an issue. I think it's benign enough to just be a documented corner case, but maybe I'm missing something.

**Comment by paf31** [comment]
What about a compromise, like a blacklist of key names?

**Comment by jbrownson** [comment]
That's an interesting idea. Would we do it by convention or checked? If we do it by convention then you have to be careful that user-generated strings don't get into the keys unchecked which seems like a recipe for disaster, so we'd probably have to add a bunch of string compares.

**Comment by michaelficarra** [comment]
@paf31 I think libraries that make that assumption about the implementation of `StrMap` are simply broken. Where was that guarantee made? Whatever they choose to use should come from purescript-foreign, and this library should not have to be concerned about those use cases.

**Comment by jbrownson** [comment]
Yeah it does seem short-sighted to have such a wart on a key library in purescript to avoid being more explicit about that use case. Foreign seems like the right spot to capture a thing like that.

**Comment by paf31** [comment]
If we added it to foreign, how would we handle this same issue?

**Comment by paf31** [comment]
I mean, you still need an FFI type for homogeneous JS objects, and likely would still want to treat such a thing like a map.

**Comment by michaelficarra** [comment]
@paf31 Treating a homogenous JS value as a map just doesn't work with keys like `__proto__`. If the object doesn't have a `__proto__` own-property, which it almost certainly won't, accessing it will trigger the `Object.prototype.__proto__` getter/setter. Bad things will ensue. Similarly, lookups of properties like `toString`, `valueOf`, etc. will resolve at `Object.prototype` to a function. Again, bad things will ensue.

**Comment by paf31** [comment]
That's fine, but for FFI purposes, we need a type which acts as a homogenous map with string keys. For example, typing the headers object on node HTTP request, it makes sense to use such a type. Using `foreign` is overkill IMO, and just plain too difficult. If we want a map type which is backed by a JS object (and I do, for one), then we have to deal with bad keys without mangling every key. We could feasibly implement such an FFI type separately from `StrMap`, but it seems a shame to duplicate all the work. What about just throwing an exception if `get` or `put` uses a bad key? How often are you really going to create a key called `__proto__` anyway?

**Comment by jbrownson** [comment]
The problem isn't that you'll want to put that key in, the problem is that if you're not careful you could expose yourself to user-facing bugs where they type __proto__ somewhere and trigger undesired behavior. Why would the use type "__proto__"? Well I just did it twice in this message, or if you're doing more than front-end stuff it could be a security problem.

Here's from the article I linked in #44: http://www.2ality.com/2012/01/objects-as-maps.html

> Think this exercise is academic and doesn't arise in real systems? As observed at a support thread, until recently, on all non-IE browsers, if you typed "__proto__" at the beginning of a new Google Doc, your Google Doc would hang. This was tracked down to such a buggy use of an object as a string map. (To avoid such problems, Caja is shifting to using StringMap.js, which does seem safe on all platforms.)

**Comment by paf31** [comment]
Fair enough, but I'm not against this PR in general, I just want to find a less heavy-handed solution if it's possible, like a blacklist of unsupported keys. We could fail fast and throw and exception, or modify those bad keys, but I'd like to keep the FFI support. Like it or not, that _is_ an existing use case for this module.

**Comment by jbrownson** [comment]
We could conditionally escape only the dangerous keys and then escape the escape prefix, more clearly document that you shouldn't rely on the ffi representation of the map, "fix" the libraries that do over time, then convert to the solution in this pr.

**Comment by paf31** [comment]
Let's discuss what it would take to provide a library with similar, safe functionality to the current implementation for FFI libraries. If we make a major version bump, and can provide an alternative implementation at the same time, that would be okay, I think.

Basically, it amounts to safe conversion functions to and from `StrMap`. Perhaps `Data.StrMap` could even provide those functions, just by modifying keys. In that case, they'd either have to be marked unsafe, or filter out any bad keys.

**Comment by jbrownson** [comment]
I went to go look at the uses in `purescript-css` and `purescript-node-http`, but I didn't see any reference to `purescript-maps` in `purescript-css`? https://github.com/slamdata/purescript-css/blob/master/bower.json

Would this new type go in `purescript-maps`, or `purescript-foreign`? `purescript-foreign` seems more intuitive to me, but I could be misassuming what the intention of that lib is. It seems to fit w/ `Data.Foreign.Null`/etc. It would make the name obvious: `Data.Foreign.StrMap`. Then we'd just have to decide what to do w/ the tricky keys, maybe even just ignore the problem in the code but document it, or fail early w/ a crash. I don't really have a preference as all options are pretty unfortunate :\.

**Comment by paf31** [comment]
This problem is worse than just `StrMap`:

```purescript
main = log { __proto__ : "hello" }.__proto__
```

prints

```
[Object object]
```

**Comment by garyb** [comment]
:see_no_evil:

**Comment by hdgarrood** [comment]
Assuming my PR gets merged, [node-child-process](https://github.com/joneshf/purescript-node-child-process) will use a `StrMap String` for the `env` parameter. This is exactly what the [node API](https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options) expects, so I'm not sure how else it should be represented. Likewise for the return value of `process.env`. My impression was that this kind of thing is exactly what `StrMap` was intended to be used for - what else, if not this?

I'm not sure exactly what the Node API will do if you want to spawn a child process and set a `__proto__` environment variable; is that API pretending this same problem doesn't exist? And if JS APIs generally pretend this problem doesn't exist, I guess we have to follow suit.

To get a safe version, maybe we could avoid duplicating the work by moving the current implementation to `foreign` and adding a key blacklist, and then implementing a safe version here based on it, which is the same except that it mangles keys.

**Comment by garyb** [comment]
Yeah, I'm pretty sure it's pretending the problem doesn't exist. Most JS code ignores things like this.

**Comment by LiamGoodacre** [comment]
This is quite old now.  I wonder if we could benefit from `Partial` with this - by exploding on black-listed keys.  I don't see much reason to escape the keys, I thought the idea was specifically that a `StrMap` is a JavaScript object.  If someone wants a "safe" map then they can use `Map String`.  I do feel that the name `StrMap` is potentially misleading though: it suggests that "if you want a map with string keys then this one is more efficient".  Whereas it is actually "this is backed by a JavaScript object".  Similarly with the documentation: "This module defines a type of native Javascript maps which require the keys to be strings." should really be "JavaScript objects" as there is a thing called `Map` in JavaScript: [mozilla-docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map).

**Comment by paf31** [comment]
I like @LiamGoodacre's idea of throwing on blacklisted keys, but I don't know how I feel about `Partial`. It seems like _every_ function is going to need a `Partial` constraint.

What about a first version with no `Partial` constraints, and a patch release, and then reconsidering whether we want to add it and make a major release after that?

**Comment by LiamGoodacre** [comment]
Also I wonder how well this would perform if backed by a real JavaScript `Map`.  Then we wouldn't need to do anything with the keys.

**Comment by michaelficarra** [comment]
Closing since this is obviously not the implementation we want. Feel free to continue this discussion here. I am personally against making `StrMap` access partial. Using `Object.create(null)` or setting via `Object.defineProperty` would both be preferable. Nobody cares about ES3 support any more anyway. If you come to a decision, I'll create another PR with the implementation.

**Pull request closed without merging**
