### PR TITLE
New functions: filterValue and filterKey

### PR DESCRIPTION
**Pull request by michal-jewel**
These are a convenient way to filter either by key or value.

### CODE REVIEW

**Comment by hdgarrood** [comment]
Looks good, I just have a few points:

* I think `filterKeys` and `filterValues` would be better names for these functions
* This implementation is going to be quadratic, as each `insert` must copy the entire object. Ideally the implementation would use ST.
* There's no need to define a new `newtype` in the tests, you can just use the existing `TestStrMap` together with an explicit type signature to signal that you want `Int` for the keys, like the other tests do.

**Comment by paf31** [comment]
Thanks for the PR, I will reference this in the release notes, but I've merged #97 instead, since it was a little more up to date.

**Comment by michal-jewel** [comment]
Great! Whatever solves the issue :-).

**Comment by michal-jewel** [comment]
I used my own version meanwhile waiting these 6 months.

**Comment by paf31** [comment]
Sorry you had to wait. In future, if you don't receive an update promptly, please post a comment, since we have a lot of PRs open, and some do tend to slip through the cracks without reminders.

**Pull request closed without merging**
